apiVersion: apps/v1
kind: Deployment
metadata:
  name: KakaoMessages
  labels:
    app: KakaoMessages
spec:
  replicas: 1
  selector:
    matchLabels:
      app: KakaoMessages
  template:
    metadata:
      labels:
        app: KakaoMessages
    spec:
      containers:
        - name: KakaoMessages
          image: username/KakaoMessages:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5