apiVersion: apps/v1
kind: Deployment
metadata:
  name: kakaomessages
  labels:
    app: kakaomessages
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kakaomessages
  template:
    metadata:
      labels:
        app: kakaomessages
    spec:
      containers:
        - name: kakaomessages
          image: admin35.azurecr.io/kakaomessages:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5